set (mui_h
	src/storage/bin.h
	src/communication/comm_factory.h
	src/communication/comm.h
	src/communication/comm_mpi.h
	src/communication/comm_mpi_smart.h
	src/communication/comm_tcp.h
	src/config.h
	src/general/dim.h
	src/storage/dynstorage.h
	src/general/endian_traits.h
	src/general/exception.h
	src/geometry/geometry.h
	src/comunication/lib_dispatcher.h
	src/comunication/lib_mpi_helper.h
	src/comunication/lib_mpi_multidomain.h
	src/comunication/lib_mpi_split.h
	src/comunication/lib_singleton.h
	src/comunication/lib_uri.h
	src/comunication/message/message.h
	src/mui.h
	src/geometry/point.h
	src/communication/message/reader_variable.h
	src/samplers/sampler.h
	src/geometry/span.h
	src/storage/spatial_storage.h
	src/storage/stream.h
	src/storage/stream_ordered.h
	src/storage/stream_string.h
	src/storage/stream_tuple.h
	src/storage/stream_unordered.h
	src/storage/stream_vector.h
	src/uniface.h
	src/general/util.h
	src/storage/virtual_container.h
	src/samplers/spatial/sampler_exact.h
	src/samplers/spatial/sampler_gauss.h
	src/samplers/spatial/sampler_mov_avg.h
	src/samplers/spatial/sampler_nn.h
	src/samplers/spatial/sampler_null.h
	src/samplers/spatial/sampler_pseudo_n2_linear.h
	src/samplers/spatial/sampler_pseudo_nn.h
	src/samplers/spatial/sampler_rbf.h
	src/samplers/spatial/sampler_shepard_quintic.h
	src/samplers/spatial/sampler_sph_quintic.h
	src/samplers/spatial/sampler_sum_quintic.h
	src/samplers/temporal/temporal_sampler_exact.h
	src/samplers/temporal/temporal_sampler_gauss.h
	src/samplers/temporal/temporal_sampler_mean.h
	src/samplers/temporal/temporal_sampler_null.h
	src/samplers/temporal/temporal_sampler_sum.h
	src/samplers/algorithm/algo_aitken.h
	src/samplers/algorithm/algo_fixed_relaxation.h
	src/samplers/algorithm/algo_null.h
)
